### ISSUE TITLE
Remplacer "Les fondateurs" par "L'equipe"

### ISSUE THREAD

**Issue by roblabla** [Seed-Up/seedup-1#12]
On peut reprendre le carousel qui se trouve dans l'ancienne page rejoignez-nous. Faudrait mettre les fleches du carousel sur les cote.

**Comment by BenjaminPoilve** [comment]
fleches a gerer

**Comment by BenjaminPoilve** [comment]
ajouter moi paul rob

**Comment by edelangh** [comment]
Done
