### ISSUE TITLE
Recreer la fiche projet

### ISSUE THREAD

**Issue by roblabla** [Seed-Up/seedup-1#8]
La modal existante est toute buggue, ce serait cool qu'elle soit pas buggue : 
- Lorsqu'on drag sur le cote, qu'elle disparaisse pas
- Lorsqu'on clique sur l'overlay, qu'elle disparaisse

Changement de texte?

**Comment by BenjaminPoilve** [comment]
le click sur le coté n'est pas reglé mais le reste oui.
